export const dictMimetypesDevSafe = {
  '.ts': 'application/typescript',
  '.tsx': 'application/typescript',
  '.js': 'application/javascript',
  '.jsx': 'application/javascript',
  '.mjs': 'application/javascript',
  '.cjs': 'application/javascript',
  '.json': 'application/json',
  '.map': 'application/json',
  '.md': 'text/markdown',
  '.yml': 'application/x-yaml',
  '.yaml': 'application/x-yaml',
  '.env': 'text/plain',
  '.log': 'text/plain',
  '.gitignore': 'text/plain',
  '.dockerfile': 'text/plain',
  '.lock': 'text/plain', // package-lock, yarn.lock, etc
  '.config': 'text/plain',
  '.pem': 'application/x-pem-file',
  '.crt': 'application/x-x509-ca-cert',
  '.key': 'application/x-pem-file',
};
